"use client";
import { FormEvent, useEffect, useState } from "react";
type Row = Record<string, string | number | undefined> & { _id: string };
type Field = { name: string; label: string; type?: "text"|"number"|"textarea"|"image"|"select"; options?: {label:string; value:string}[] };
export default function AdminCrud({ title, endpoint, fields }: { title:string; endpoint:string; fields:Field[] }){
  const [rows,setRows]=useState<Row[]>([]); const [editing,setEditing]=useState<Row|null>(null); const [form,setForm]=useState<Record<string,string>>(Object.fromEntries(fields.map(f=>[f.name,""])));
  async function load(){ const res=await fetch(endpoint,{cache:"no-store"}); const data=(await res.json()) as Row[]; setRows(data); }
  useEffect(()=>{ void load(); },[]);
  async function upload(file: File){ const fd=new FormData(); fd.append("file",file); const res=await fetch("/api/upload",{method:"POST",body:fd}); const data=await res.json() as {url:string}; return data.url; }
  async function submit(e:FormEvent){ e.preventDefault(); const payload:Record<string,string|number>= {...form}; fields.forEach(f=>{ if(f.type==="number") payload[f.name]=Number(form[f.name]||0); }); const url=editing?`${endpoint}/${editing._id}`:endpoint; await fetch(url,{method:editing?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}); setEditing(null); setForm(Object.fromEntries(fields.map(f=>[f.name,""]))); await load(); }
  async function remove(id:string){ await fetch(`${endpoint}/${id}`,{method:"DELETE"}); await load(); }
  return <main className="mx-auto max-w-6xl px-4 py-10"><h1 className="mb-6 text-3xl font-black">{title}</h1><form onSubmit={submit} className="grid gap-3 rounded-2xl bg-white p-5 shadow">
    {fields.map(f=> f.type==="textarea" ? <textarea key={f.name} placeholder={f.label} value={form[f.name]||""} onChange={e=>setForm({...form,[f.name]:e.target.value})} className="rounded-xl border p-3"/> : f.type==="image" ? <input key={f.name} type="file" accept="image/*" onChange={async e=>{const file=e.target.files?.[0]; if(file) setForm({...form,[f.name]:await upload(file)});}} className="rounded-xl border p-3"/> : f.type==="select" ? <select key={f.name} value={form[f.name]||""} onChange={e=>setForm({...form,[f.name]:e.target.value})} className="rounded-xl border p-3"><option value="">{f.label}</option>{f.options?.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select> : <input key={f.name} type={f.type||"text"} placeholder={f.label} value={form[f.name]||""} onChange={e=>setForm({...form,[f.name]:e.target.value})} className="rounded-xl border p-3"/>)}
    <button className="rounded-xl bg-orange-700 p-3 font-bold text-white">{editing?"Update":"Add"}</button></form><div className="mt-8 space-y-3">{rows.map(r=><div key={r._id} className="flex items-center justify-between rounded-xl bg-white p-4 shadow"><div><b>{String(r.name||r.title)}</b><p className="text-sm text-gray-500">{r.imageUrl ? String(r.imageUrl).slice(0,60) : r.slug}</p></div><div className="flex gap-2"><button onClick={()=>{setEditing(r); setForm(Object.fromEntries(fields.map(f=>[f.name,String(r[f.name] ?? "")])));}} className="rounded-lg border px-3 py-2">Edit</button><button onClick={()=>remove(r._id)} className="rounded-lg bg-red-600 px-3 py-2 text-white">Delete</button></div></div>)}</div></main>
}
